const suggestionsDatabase = [
  "How to get a job at Google",
  "How to get gum out of hair",
  "How to get people to like me",
  "How to get a job at Amazon",
  "Sasuke is a trash character",
  "How high is the empire state building",
  "Her by Tyler The Creator",
  "Halo 9 release date",
  "HxH is the best anime",
  "Halos oranges vs Cuties oranges",
  "Is Morbius good?",
  "When is JavaScript 2 coming out",
  "Can React 18 solve the worlds problems",
  "web 3",
  "atlanta weather",
  "nba playoffs",
  "outlook",
  "offline horse racing",
  "gravity falls 2",
  "Gantu was the good guy in lilo and stitch",
  "Alfa Romeo,4C,3411",
  "Chrysler,Royal,20",
  "Courage the cowardly dog",
  "Family means no one gets left behind",
  "Banana joe",
  "Bank of america",
  "Peanut butter jelly time",
  "Manga sites",
  "Marco's Pizza",
  "Jenga 3 release date",
  "Dominoes taste like dirt",
  "Electric eels",
  "Race cars",
  "Radical foods",
  "Time traveling donkey",
  "Yo-yo ma",
  "Yo yo gabba gabba",
  "Let me talk to him, its your boy black guy",
  "Louis vuitton",
  "ups tracking",
  "usps lost my package again",
  "Obito is a trasher character",
  "Kenya",
  "Kakashi is a good character"
];

export { suggestionsDatabase };